name: Generate project list

on:
    schedule:
        - cron: "50 7 1 * *" #First day of each mounth
    workflow_dispatch:

jobs:
    integrations:
        name: Generate Projects list
        if: github.repository_owner == 'NicolasRenault'
        runs-on: ubuntu-latest
        steps:
            - name: Check out code using Git
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Run generate contribution list script
              run: npm run github:project
              env:
                  GITHUB_TOKEN: ${{ secrets.PROJECTS_TOKEN }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Update projects list
                  title: Update projects list
                  body: |
                      This PR was created by the GitHub Actions workflow **Mounthly**. 

                      The commit hash is _${{ github.sha }}_.
                  branch: projects-list
                  delete-branch: true
